### ISSUE TITLE
Filter Options

### ISSUE THREAD

**Issue by maurovieirareis** [pawDesktopApp/public-feeling#1]
Is possible remove some filters from the search, like Reddit filter who I don't use?

**Comment by Mteixeira88** [comment]
I'll study the best way of doing that, so in versions 0.2.n it will not be implemented, but in version 0.3.0 I'll try to implement that feature.

Thanks

**Comment by Mteixeira88** [comment]
Filters were added to the app in version 0.3.0.

Thanks for the help,
Miguel Teixeira
